name: Deploy loginkey GCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    environment: loginkey-prod
    env:
      IMAGE_NAME: gcr.io/loginkey/loginkey:latest
      PROJECT_ID: loginkey
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Login to GCP
      - name: Goofle cloud auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # gcloud configure docker
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # build image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      # push image to registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      # deploy image
      - name: Deploy Docker image
        run: >
          gcloud run deploy loginkey
          --image $IMAGE_NAME
          --region us-central1
          --memory 128Mi
          --min-instances 0
          --max-instances 1
          --platform managed
          --port 5555
          --set-env-vars FASTAPI_PORT=5555
          --allow-unauthenticated