#name: Deploy loginkey GCP
#
#env:
#  SERVICE_NAME: loginkey
#  PROJECT_ID: loginkey
#  DOCKER_IMAGE_URL: us-east1-docker.pkg.dev/loginkey/loginkey:latest
#
#on:
#  push:
#    branches: [main]
#
#jobs:
#  deploy:
#    name: Setup Gcloud Account
#    runs-on: ubuntu-latest
#    steps:
#      # Git checkout
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      # Login to GCP
#      - name: Goofle cloud auth
#        uses: 'google-github-actions/auth@v2'
#        with:
#          credentials_json: ${{ secrets.GCP_SA_KEY }}
#          project_id: loginkey
#
#      # gcloud configure docker
#      - name: Configure Docker
#        run: gcloud auth configure-docker --quiet
#
#      # build image
#      - name: Build Docker image
#        run: docker build -t $IMAGE_NAME .
#
#      # push image to registry
#      - name: Push Docker image
#        run: docker push $IMAGE_NAME
#
#      # deploy image
#      - name: Deploy Docker image
#        run: >
#          gcloud run deploy loginkey
#          --image $IMAGE_NAME
#          --region us-central1
#          --memory 128Mi
#          --min-instances 0
#          --max-instances 1
#          --platform managed
#          --port 5555
#          --set-env-vars FASTAPI_PORT=5555
#          --allow-unauthenticated

name: Deploy to Cloud Run

env:
  SERVICE_NAME: loginkey
  PROJECT_ID: loginkey
  DOCKER_IMAGE_URL: us-east1-docker.pkg.dev/loginkey/loginkey
on:
  push:
    branches:
      - main


jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    # Definir a variável aqui torna-a disponível para todos os passos abaixo
    env:
      DOCKER_IMAGE_URL: us-east1-docker.pkg.dev/loginkey/loginkey/loginkey

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          echo "A construir e a enviar para: ${{ env.DOCKER_IMAGE_URL }}:latest"
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo "A implementar a imagem: ${{ env.DOCKER_IMAGE_URL }}:latest"
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated